name: Setup triggers box comment

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  create-triggers-box-comment:
    name: Create triggers box comment
    runs-on: ubuntu-latest
    env:
      REPO: ${{ github.repository }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      COMMIT_HASH: ${{ github.event.pull_request.head.sha }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      HEAD_REF: ${{ github.head_ref }}
      ACTION_BOT: "luanlai2201"
    steps:
      - name: Find existing comment
        id: find_comment
        run: |
          comments_url="https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments"
          # Fetch all comments, then find the first comment made by $ACTION_BOT with the correct hidden ID

          comment_id=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "$comments_url" |
            jq -r --arg ACTION_BOT "$ACTION_BOT" --arg PR_NUMBER "$PR_NUMBER" '.[] | select(.user.login == $ACTION_BOT and (.body | test("<!-- workflow-triggers--hero-design-\($PR_NUMBER) -->"))) | .id' | head -1)
          echo "comment_id=$comment_id" >> $GITHUB_OUTPUT

      - name: Create/edit trigger comment
        env:
          COMMENT_ID: ${{ steps.find_comment.outputs.comment_id }}
        run: |
          echo "Starting script for PR #$PR_NUMBER on repo $REPO at commit $COMMIT_HASH"
          echo "Formulating the GitHub comment..."

          encoded_branch_name=$(echo "$HEAD_REF" | tr -d '\n' | jq -sRr @uri)

          generate_workflow_markdown() {
            local workflow_name=$1
            local workflow_url="https://github.com/$REPO/actions/workflows/${workflow_name}.yml?query=branch%3A${encoded_branch_name}"

            echo "[ ] \`${workflow_name}\` on GitHub Actions at this [workflow]($workflow_url)."
          }

          message=$(cat <<- EOF
          # Workflow triggers <!-- workflow-triggers--hero-design-$PR_NUMBER -->
            This comment use to trigger the workflow for PR #$PR_NUMBER on repo $REPO at commit $COMMIT_HASH.
            **This message is auto generated by the bot. Please do not edit this message without check the checkbox.**
          ## Required
          - $(generate_workflow_markdown "build-dev")

          _This comment is generated against commit $COMMIT_HASH, updated at:_
          - _$(TZ='Asia/Ho_Chi_Minh' date "+%Y-%m-%d - %H:%M:%S (Asia/Ho Chi Minh)")_
          - _$(TZ='Australia/Sydney' date "+%Y-%m-%d - %H:%M:%S (Australia/Sydney)")_
          EOF
          )
          json_payload=$(jq -n --arg body "$message" '{body: $body}')
          if [ -z "$COMMENT_ID" ]; then
            echo "Creating new comment..."
            curl -s \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              -X POST \
              -d "$json_payload" \
              "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments"
          else
            echo "Updating existing comment..."
            curl -s \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              -X PATCH \
              -d "$json_payload" \
              "https://api.github.com/repos/$REPO/issues/comments/$COMMENT_ID"
          fi
          echo "Comment posted or updated."
